excluded:
  - Pods

disabled_rules:
  # Cocoaのdelegate method長くなる傾向があるし単純に長さだけしか見てない警告はあまり意味がないので
  - line_length
  - identifier_name
  - function_body_length
  - switch_case_alignment
  - type_name
  - cyclomatic_complexity
  - nesting
  - force_try
  - multiple_closures_with_trailing_closure
  - implicit_getter
  - type_body_length
  - function_parameter_count

file_length:
  - 800 # warning
  - 1000 # error
